name        = "61st Auxilary Mod V0.0.0";
author      = "61st Auxilary Mod Team";
picture     = "\z\Aux61st\addons\main\data\textures\61st.paa";
logosmall   = "\z\Aux61st\addons\main\data\textures\61st.paa";
logo        = "\z\Aux61st\addons\main\data\textures\61st.paa";
action      = "https://61st-regiment.com";
overview    = "The Auxiliary mod for the 61st Cavalry Regiment";
hidePicture = 0;
hideName    = 0;
